<!-- HTML header for doxygen 1.8.13-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.13"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>The deal.II Library: deal_II_exceptions Namespace Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
<link href="stylesheet.css" rel="stylesheet" type="text/css"/>
<link rel="SHORTCUT ICON" href="deal.ico"></link>
<script type="text/javascript" src="custom.js"></script>
<meta name="author" content="The deal.II Authors <authors@dealii.org>"></meta>
<meta name="copyright" content="Copyright (C) 1998 - 2017 by the deal.II authors"></meta>
<meta name="deal.II-version" content="9.0.0-pre"></meta>
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectlogo"><img alt="Logo" src="logo200.png"/></td>
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">
   &#160;<span id="projectnumber">Reference documentation for deal.II version 9.0.0-pre</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.13 -->
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#namespaces">Namespaces</a> &#124;
<a href="#func-members">Functions</a>  </div>
  <div class="headertitle">
<div class="title">deal_II_exceptions Namespace Reference<div class="ingroups"><a class="el" href="group__Exceptions.html">Exceptions and assertions</a></div></div>  </div>
</div><!--header-->
<div class="contents">
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:namespacedeal__II__exceptions_1_1internals"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacedeal__II__exceptions_1_1internals.html">internals</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a8c3f112b3e59832e4ceac8f6633672be"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacedeal__II__exceptions.html#a8c3f112b3e59832e4ceac8f6633672be">set_additional_assert_output</a> (const char *const p)</td></tr>
<tr class="separator:a8c3f112b3e59832e4ceac8f6633672be"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9daa5d2e7e7d5b374e6a71e66472360d"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacedeal__II__exceptions.html#a9daa5d2e7e7d5b374e6a71e66472360d">suppress_stacktrace_in_exceptions</a> ()</td></tr>
<tr class="separator:a9daa5d2e7e7d5b374e6a71e66472360d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3953411a9013d21af68e53fa5bbd4f8e"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacedeal__II__exceptions.html#a3953411a9013d21af68e53fa5bbd4f8e">disable_abort_on_exception</a> ()</td></tr>
<tr class="separator:a3953411a9013d21af68e53fa5bbd4f8e"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>In this namespace, functions in connection with the Assert and AssertThrow mechanism are declared. </p>
</div><h2 class="groupheader">Function Documentation</h2>
<a id="a8c3f112b3e59832e4ceac8f6633672be"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a8c3f112b3e59832e4ceac8f6633672be">&#9670;&nbsp;</a></span>set_additional_assert_output()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void deal_II_exceptions::set_additional_assert_output </td>
          <td>(</td>
          <td class="paramtype">const char *const&#160;</td>
          <td class="paramname"><em>p</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Set a string that is printed upon output of the message indicating a triggered <code>Assert</code> statement. This string, which is printed in addition to the usual output may indicate information that is otherwise not readily available unless we are using a debugger. For example, with distributed programs on cluster computers, the output of all processes is redirected to the same console window. In this case, it is convenient to set as additional name the name of the host on which the program runs, so that one can see in which instance of the program the exception occurred.</p>
<p>The string pointed to by the argument is copied, so doesn't need to be stored after the call to this function.</p>
<p>Previously set additional output is replaced by the argument given to this function. </p>

<p class="definition">Definition at line <a class="el" href="base_2exceptions_8cc_source.html#l00047">47</a> of file <a class="el" href="base_2exceptions_8cc_source.html">exceptions.cc</a>.</p>

</div>
</div>
<a id="a9daa5d2e7e7d5b374e6a71e66472360d"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a9daa5d2e7e7d5b374e6a71e66472360d">&#9670;&nbsp;</a></span>suppress_stacktrace_in_exceptions()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void deal_II_exceptions::suppress_stacktrace_in_exceptions </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Calling this function disables printing a stacktrace along with the other output printed when an exception occurs. Most of the time, you will want to see such a stacktrace; suppressing it, however, is useful if one wants to compare the output of a program across different machines and systems, since the stacktrace shows memory addresses and library names/paths that depend on the exact setup of a machine. </p>

<p class="definition">Definition at line <a class="el" href="base_2exceptions_8cc_source.html#l00054">54</a> of file <a class="el" href="base_2exceptions_8cc_source.html">exceptions.cc</a>.</p>

</div>
</div>
<a id="a3953411a9013d21af68e53fa5bbd4f8e"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a3953411a9013d21af68e53fa5bbd4f8e">&#9670;&nbsp;</a></span>disable_abort_on_exception()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void deal_II_exceptions::disable_abort_on_exception </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Calling this function switches off the use of <code>std::abort()</code> when an exception is created using the <a class="el" href="group__Exceptions.html#ga70a0bb353656e704acf927945277bbc6">Assert()</a> macro. Instead, the Exception will be thrown using 'throw', so it can be caught if desired. Generally, you want to abort the execution of a program when <a class="el" href="group__Exceptions.html#ga70a0bb353656e704acf927945277bbc6">Assert()</a> is called, but it needs to be switched off if you want to log all exceptions created, or if you want to test if an assertion is working correctly. This is done for example in regression tests. Please note that some fatal errors will still call abort(), e.g. when an exception is caught during exception handling. </p>

<p class="definition">Definition at line <a class="el" href="base_2exceptions_8cc_source.html#l00061">61</a> of file <a class="el" href="base_2exceptions_8cc_source.html">exceptions.cc</a>.</p>

</div>
</div>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.13-->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by &#160;<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/>
</a> 1.8.13
</small></address>
</body>
</html>
